export const MAX_CHAT_MESSAGE_CHARS = 2000;
export const MAX_EXPLAIN_QUESTION_CHARS = 3000;
export const MAX_SUMMARY_CONTENT_CHARS = 8000;
export const MAX_PRACTICE_SUBJECT_CHARS = 120;
export const MAX_SCHEDULE_SUBJECT_COUNT = 8;
export const MAX_SCHEDULE_SUBJECT_CHARS = 120;
